data class JoItemX(
    val AR_Keywords: List<ARKeywordX>,
    val AR_Liens: List<ARLienX>,
    val ATexte: String,
    val A_PDFFileName: String,
    val AnneeJO: String,
    val Date Publication AR: String,
    val Date Signature AR: String,
    val Date Signature FR: String,
    val Date publication FR: String,
    val FR_Keywords: List<FRKeywordX>,
    val FTexte: String,
    val F_PDFFileName: String,
    val NumJO: String,
    val NumSGG: String,
    val Organe AR: String,
    val Organe FR: String,
    val Page AR: String,
    val Page FR: String,
    val Secteurs: List<SecteurX>,
    val Sommaire AR: String,
    val Sommaire FR: String,
    val Type Texte AR: String,
    val Type Texte FR: String
)